@startuml

interface IPaymentProcessor {
    +processPayment(amount: float): boolean
}

interface IDeliveryService {
    +scheduleDelivery(orderId: string, deliveryDate: string): boolean
}

class ClientOrder {
    +string orderId
    +string clientId
}

class Client {
    +string id
    +string email
}

class OrderProduct {
    +int quantity
    +string orderId
    +string productId
}

class Product {
    +string id
    +string name
    +float price
    +ProductStatus status
}

class ProductStatus {
    +INSTOCK
    +OUTOFSTOCK
    +PREORDER
}

class Category {
    +string id
    +string name
}

class Order {
    +string id
    +float totalPrice
    +OrderStatus status
}

class Payment implements IPaymentProcessor {
    +string id
    +string method
    +boolean confirmed

    +processPayment(amount: float): boolean
}

class Delivery implements IDeliveryService {
    +string id
    +string method
    +string deliveryDate

    +scheduleDelivery(orderId: string, deliveryDate: string): boolean
}

class OrderStatus {
    +PENDING
    +PROCESSING
    +SHIPPED
    +DELIVERED
}

Order "1" -- "0..*" OrderStatus : has >
Product "1" -- "0..*" ProductStatus : has >
Order "0..*" -- "1" Payment : processed by >
Order "0..*" -- "1" Delivery : delivered by >
Category "1" -- "0..*" Product : categorizes >

' Many-to-Many relationship between Order and Product
Order "0..*" -- "0..*" OrderProduct : contains >
Product "0..*" -- "0..*" OrderProduct : includes >
Client "0..*" -- "0..*" ClientOrder : contains >
Order "0..*" -- "0..*" ClientOrder : includes >

@enduml