@startuml


class clientOrder {
    +string orderId
    +string clientId
}

class Client {
    +string id
    +string email
}

class orderProduct {
    +int quantity
    +string orderId
    +string productId
}

class Product {
    +string id
    +string name
    +float price
    +productStatus status
}

class productStatus {
    +INSTOCK
    +OUTOFSTOCK
    +PREORDER
}

class Category {
    +string id
    +string name
}

class Order {
    +string id
    +float totalPrice
    +orderStatus status
}

class Payment {
    +string id
    +string method
    +boolean confirmed
}

class Delivery {
    +string id
    +string method
    +string deliveryDate
}

class orderStatus {
    +PENDING
    +PROCESSING
    +SHIPPED
    +DELIVERED
}

Order "1" -- "0..*" orderStatus : has >
Product "1" -- "0..*" productStatus : has >
' Product "1" -- "0..*" Order : contains >
Order "0..*" -- "1" Payment : processed by >
Order "0..*" -- "1" Payment : processed by >
Order "0..*" -- "1" Delivery : delivered by >
Category "1" -- "0..*" Product : categorizes >
' Many-to-Many relationship between Order and Product
Order "0..*" -- "0..*" orderProduct : contains >
Product "0..*" -- "0..*" orderProduct : includes >
' Many-to-Many relationship between Order and Product
Client "0..*" -- "0..*" clientOrder : contains >
Order "0..*" -- "0..*" clientOrder : includes >

@enduml