openapi: 3.0.0

info:
  title: Eshop API
  description: API pro správu eshopu s podporou OIDC
  version: 1.1.1

servers:
  - url: https://eshop.example.com/v1

components:
  securitySchemes:
    OIDC:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.example.com/oauth2/authorize
          tokenUrl: https://auth.example.com/oauth2/token
          scopes:
            openid: Získání identifikátoru uživatele
            profile: Přístup k uživatelskému profilu
            email: Přístup k uživatelské emailové adrese
            products.read: Čtení seznamu produktů
            products.create: Přidání nového produktu
            products.delete: Aktualizace produktu
            products.update: Smazání produktu
            categories.read: Čtení seznamu kategorií
            categories.create: Přidání nové kategorie
            orders.read: Čtení seznamu objednávek
            orders.create: Vytvoření nové objednávky
            orders.update: Aktualizace objednávky
            payments.create: Vytvoření platby

  parameters:
    TraceStateHeader:
      name: tracestate
      in: header
      required: false
      description: "Korelaci žádosti pro sledování toku dat."
      schema:
        type: string

    ClientIPHeader:
      name: X-Client-IP
      in: header
      required: false
      description: "IP adresa klienta, který provádí požadavek."
      schema:
        type: string
        format: ipv4

paths:
  /products:
    get:
      summary: Získat seznam produktů
      operationId: getProducts
      security:
        - OIDC: [openid, profile, products.read]
      parameters:
        - $ref: "#components/parameters/TraceStateHeader"
        - $ref: "#components/parameters/ClientIPHeader"
      responses:
        "200":
          description: Úspěšná odpověď se seznamem produktů
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: "Produkt A"
                    price:
                      type: number
                      format: float
                      example: 19.99

    post:
      summary: Přidat nový produkt
      operationId: addProduct
      security:
        - OIDC: [openid, profile, products.create]
      parameters:
        - $ref: "#components/parameters/TraceStateHeader"
        - $ref: "#components/parameters/ClientIPHeader"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Nový Produkt"
                price:
                  type: number
                  format: float
                  example: 29.99
      responses:
        "201":
          description: Produkt byl úspěšně přidán
        "400":
          description: Chybný požadavek
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Chybí povinné pole 'name'."

  /orders:
    get:
      summary: Získat seznam objednávek
      operationId: getOrders
      security:
        - OIDC: [openid, profile, orders.read]
      parameters:
        - $ref: "#components/parameters/TraceStateHeader"
        - $ref: "#components/parameters/ClientIPHeader"
      responses:
        "200":
          description: Úspěšná odpověď se seznamem objednávek
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    totalPrice:
                      type: number
                      format: float
                      example: 199.99
                    status:
                      type: string
                      example: "Zpracováno"

    post:
      summary: Vytvořit novou objednávku
      operationId: createOrder
      security:
        - OIDC: [openid, profile, orders.create]
      parameters:
        - $ref: "#components/parameters/TraceStateHeader"
        - $ref: "#components/parameters/ClientIPHeader"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productIds:
                  type: array
                  items:
                    type: integer
                  example: [1, 2]
                quantities:
                  type: array
                  items:
                    type: integer
                  example: [2, 1]
      responses:
        "201":
          description: Objednávka byla úspěšně vytvořena
        "400":
          description: Chybný požadavek
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Chybí povinné pole 'productIds'."
        "404":
          description: Produkt nenalezen
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Jeden nebo více produktů nebyly nalezeny."
  /orders/{id}:
    get:
      summary: Získat detail objednávky podle ID
      operationId: getOrderById
      parameters:
        - name: id
          in: path
          required: true
          description: ID objednávky, kterou chcete získat.
          schema:
            type: integer
            example: 1
        - $ref: "#components/parameters/TraceStateHeader"
        - $ref: "#components/parameters/ClientIPHeader"
      security:
        - OIDC: [openid, profile, orders.read]
      responses:
        "200":
          description: Úspěšná odpověď s detaily objednávky
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  totalPrice:
                    type: number
                    format: float
                    example: 199.99
                  status:
                    type: string
                    example: "Zpracováno"
